version: "2.26.1"

services:
  
  backend:
    image: backend-api
    build: ./backend
    container_name: "backend-api"
    ports:
      - "5000:5000"

  frontend:
    image: frontend-app
    build: ./frontend
    container_name: "frontend-app"
    ports:
      - "3000:3000"
